### ISSUE TITLE
confusing metasploit example

### ISSUE THREAD

**Issue by JizongL** [blackhat-go/bhg#16]
Hi, I have been following your book and came across with the metasploit example and got the following error

```
2020/12/06 17:34:46 Post "http://10.0.1.6:55552/api": dial tcp 10.0.1.6:55552: i/o timeout
panic: Post "http://10.0.1.6:55552/api": dial tcp 10.0.1.6:55552: i/o timeout


goroutine 1 [running]:
log.Panicln(0xc00010dd38, 0x1, 0x1)
	/usr/local/go/src/log/log.go:365 +0xae
main.main()
	/Users/dmml/Documents/golang/hacking/metasploit/metasploit-minimal/client/main.go:19 +0x19a
exit status 2
```

it looks like it couldn't connect to the tcp connection. 

I did start the msf server and ran the following successfully
```
msf6 > load msgrpc Pass=s3cr3t ServerHost=10.0.1.6
[*] MSGRPC Service:  10.0.1.6:55552
[*] MSGRPC Username: msf
[*] MSGRPC Password: s3cr3t
[*] Successfully loaded plugin: msgrpc
```

Please give some comment and tips thanks.

**Comment by tomsteele** [comment]
So the IO timeout means Go can't talk to the TCP socket. I would confirm there is no filtering in place.
